### ISSUE TITLE
Transfer mongoid-rspec into github.com/mongoid

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-rspec#177]
I had https://github.com/mongoid kindly donated to the community by the nice folks at MongoDB. The three people who have org level admin access are currently @durran, @estolfo and myself. 

@rodrigopinto and myself had an exchange about moving this repo into that organization. I wanted to bring this up here.

If you're up for it, transfer mongoid-rspec to me and I'll move it into the org. All admins will continue having admin access, but I think it makes good sense to group mongoid projects together and have continuous support from MongoDB, the company, over the long term.

Should also add the project to http://mongoid.github.io/.

**Comment by rodrigopinto** [comment]
Hey @evansagge I was wondering if having more people engaged to maintain the gem would be nice to keep giving back to the community and make sure this helpful lib stay alive. 

Me and @dblock had exchanged some emails to think how we can keep this project active. As you started the project years ago and I became maintainer late, I don't want to take any decision without to have your points and concerns.

**Comment by rodrigopinto** [comment]
We started this chat about a year ago and nothing happens until now mainly on my side. I would like to make this move and I am pretty sure it is going to be beneficial to the community. 

As @evansagge didn't raise any concern I believe we can do it.

My only suggestion, even considering that Git already keeps a track record of everyone works, is to mention him on a credits section on the readme, considering that the gem exists because of him.

Let's do it @dblock ⁉️

**Comment by dblock** [comment]
Please! Just transfer the repo to me and I will immediately move it into mongoid.

**Comment by rodrigopinto** [comment]
@dblock did it! 😄

**Comment by dblock** [comment]
Done. @rodrigopinto You're admin on this repo so you can (re)add collaborators and such.

**Comment by rodrigopinto** [comment]
Thanks @dblock! 🎉 🎉 🎉
